# SIS:AUTO_GENERATED: Remove this line if you edit the file, otherwise it will be overwritten
add_subdirectory(example.c.1)
add_subdirectory(example.c.2)
add_subdirectory(example.c.3)
add_subdirectory(example.c.4)
add_subdirectory(example.c.5)
add_subdirectory(example.c.6)
add_subdirectory(example.c.7)
add_subdirectory(example.c.8)
